[project]
name = "xat"
version = "0"
dependencies = [
  "absl-py==2.1.0",
  "fastapi==0.110.0",
  "paddleocr==2.7.0.3",
  "paddlepaddle==2.6.0",
  "pykka==4.0.2",
  "python-multipart==0.0.9",
  "uvicorn==0.28.0",
]
