import { Navbar, NavbarContent, NavbarItem } from "@nextui-org/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "xat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <main className="flex flex-col min-h-screen max-w-screen">
            <Navbar>
              <NavbarContent justify="start">
                <NavbarItem>Your return</NavbarItem>
                <NavbarItem>Saved</NavbarItem>
              </NavbarContent>
              <NavbarContent justify="end">
                <NavbarItem>Account</NavbarItem>
                <NavbarItem>Help</NavbarItem>
              </NavbarContent>
            </Navbar>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
