name: bazel
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel
      - run: bazel build ...
      # TODO(lev1ty): uncomment when we write a test
      # - run: bazel test ...
